\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		fs2:m fs2:m c2:dim7 c2:dim7
		fs2:m fs2:m

		% me encontraba...
		fs2:m c2:dim7
		fs2:m b2:m
		fs2:m e2
		fs2:m fs2:m

		fs2:m c2:dim7
		fs2:m b2:m
		fs2:m e2

		fs1:m e1
		fs1:m b2:7sus4 b2:7

		% escuchaste mis plegarias...
		e1 gs1 a1 fs2:m b2:7
		a1 e1:/gs fs1:m b1:7
		a1 e1 fs1:m fs1:m

		% ahora que he vivido...
		fs1:m c1:dim7
		fs1:m b1:m
		fs1:m e1
		fs1:m fs1:m

		% eres el camino...
		fs1:m c1:dim7
		fs1:m b1:m
		fs1:m e1

		fs1:m e1
		fs1:m b2:7sus4 b2:7

		% escuchaste mis plegarias...
		e1 gs1 a1 fs2:m b2:7
		a1 e1:/gs fs1:m b1:7
		a1

		% hoy puedo sentir...
		e1 cs1:m a1 b1
		e1 cs1:m fs1:m b1
		b1:7 c1 b2:7sus4 b2:7

		% escuchaste mis plegarias...
		e1 gs1 a1 fs2:m b2:7
		a1 e1:/gs fs1:m b1:7
		a1 a1:m e1 e1
	}
